name: CI

on: [push]

jobs:
  Build:
    name: Build project using Ionic and Cordova
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout latest push
        uses: actions/checkout@v1
        
      - name: Setup Ionic  
        uses: coturiv/setup-ionic@v1.0.0
        
      - name: Ionic production Android build
        run: |
          ionic cordova build android
          

